enum Actions {
  INIT_SETTINGS = 'INIT_SETTINGS',
  TOGGLE_MUSIC = 'TOGGLE_MUSIC',
  TOGGLE_SFX = 'TOGGLE_SFX',
  TOGGLE_COLORBLIND = 'TOGGLE_COLORBLIND',
  COMPLETE_LEVEL = 'COMPLETE_LEVEL',
  UNLOCK_LEVEL = 'UNLOCK_LEVEL',
}

export default Actions;
